Repository Git-For-Geeks/HelloWorld-, pull requests merged in 2022-10, with the labels that each got.

#12 Added achievements section page
  achievements.html
  contactus.html
  css/achievements.css
  image/pexels-yan-krukov-6817701.jpg
  index.html
Labels: medium, git-for-geeks, hacktoberfest, hacktoberfest-accepted

#23 Sagar Dave
  FAQ.html
  index.html
Labels: medium, git-for-geeks

#25 added features in events section
  css/events.css
  events.html
  events.mp4
Labels: medium, git-for-geeks

#27 added sign up and login page and made changes in navbar
  FAQ.html
  image/faq.jpg
  index.html
  sign.css
  signup.html
Labels: medium, git-for-geeks, hacktoberfest, hacktoberfest-accepted

#28 additional features in faq
  FAQ.html
  faq.jpg
Labels: easy, git-for-geeks, hacktoberfest, hacktoberfest-accepted
